const lessonTitle = "林中小溪";

const lessonData = [
    // ===== 第1段 =====
    ["如果", "rú guǒ", "If", "Jika"],
    ["你", "nǐ", "you", "awak"],
    ["想", "xiǎng", "want", "mahu"],
    ["了解", "liǎo jiě", "to understand", "untuk memahami"],
    ["森林", "sēn lín", "forest", "hutan"],
    ["的", "de", "", ""],
    ["心灵", "xīn líng", "soul", "jiwa"],
    ["，", "", "", ""],
    ["那", "nà", "then", "maka"],
    ["你", "nǐ", "you", "awak"],
    ["就", "jiù", "then", "lalu"],
    ["去", "qù", "go", "pergi"],
    ["找", "zhǎo", "find", "cari"],
    ["一条", "yī tiáo", "a", "sebatang"],
    ["林中小溪", "lín zhōng xiǎo xī", "forest stream", "sungai kecil di hutan"],
    ["，", "", "", ""],
    ["顺着", "shùn zhe", "along", "menyusuri"],
    ["它的", "tā de", "its", "ia punya"],
    ["岸边", "àn biān", "bank", "tebing"],
    ["往", "wǎng", "towards", "ke"],
    ["上游", "shàng yóu", "upstream", "hulu"],
    ["或者", "huò zhě", "or", "atau"],
    ["下游", "xià yóu", "downstream", "hilir"],
    ["走一走", "zǒu yī zǒu", "take a walk", "berjalan-jalan"],
    ["吧", "ba", "", ""],
    ["。", "", "", ""],
    ["刚开春", "gāng kāi chūn", "Early spring", "Awal musim bunga"],
    ["的", "de", "", ""],
    ["时候", "shí hou", "when", "ketika"],
    ["，", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["就", "jiù", "then", "lalu"],
    ["在", "zài", "on", "di"],
    ["我那条", "wǒ nà tiáo", "my", "sungai"],
    ["可爱的", "kě ài de", "lovely", "yang comel"],
    ["小溪", "xiǎo xī", "stream", "sungai kecil"],
    ["的", "de", "", ""],
    ["岸边", "àn biān", "bank", "tebing"],
    ["走过", "zǒu guò", "walked", "berjalan"],
    ["，", "", "", ""],
    ["下面", "xià miàn", "below", "di bawah"],
    ["就是", "jiù shì", "is", "ialah"],
    ["我", "wǒ", "my", "saya punya"],
    ["在那儿", "zài nà r", "there", "di sana"],
    ["的", "de", "", ""],
    ["所见", "suǒ jiàn", "what I saw", "apa yang saya lihat"],
    ["、", "", "", ""],
    ["所闻", "suǒ wén", "what I heard", "apa yang saya dengar"],
    ["和", "hé", "and", "dan"],
    ["所想", "suǒ xiǎng", "what I thought", "apa yang saya fikir"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第2段

    ["我", "wǒ", "I", "saya"],
    ["看见", "kàn jiàn", "saw", "melihat"],
    ["，", "", "", ""],
    ["流水", "liú shuǐ", "flowing water", "air yang mengalir"],
    ["在", "zài", "in", "di"],
    ["浅的地方", "qiǎn de dì fang", "shallow places", "tempat yang cetek"],
    ["遇到", "yù dào", "encounter", "menemui"],
    ["云杉树根", "yún shān shù gēn", "spruce roots", "akar pokok spruce"],
    ["的", "de", "", ""],
    ["障碍", "zhàng ài", "obstacle", "halangan"],
    ["，", "", "", ""],
    ["于是", "yú shì", "so", "maka"],
    ["冲着", "chòng zhe", "rushing towards", "menghala ke"],
    ["树根", "shù gēn", "roots", "akar"],
    ["潺潺鸣响", "chán chán míng xiǎng", "gurgling", "berbunyi gemericik"],
    ["，", "", "", ""],
    ["冒出", "mào chū", "emerge", "keluar"],
    ["气泡", "qì pào", "bubbles", "buih-buih"],
    ["来", "lái", "", ""],
    ["。", "", "", ""],
    ["这些", "zhè xiē", "These", "Buih-buih ini"],
    ["气泡", "qì pào", "bubbles", "buih-buih"],
    ["一冒出来", "yī mào chū lái", "once they emerge", "sebaik sahaja keluar"],
    ["，", "", "", ""],
    ["就", "jiù", "then", "lalu"],
    ["迅速地", "xùn sù de", "quickly", "dengan cepat"],
    ["漂走", "piāo zǒu", "drift away", "hanyut"],
    ["，", "", "", ""],
    ["不久", "bù jiǔ", "soon", "tidak lama"],
    ["即", "jí", "then", "lalu"],
    ["破灭", "pò miè", "burst", "pecah"],
    ["，", "", "", ""],
    ["但", "dàn", "but", "tetapi"],
    ["大部分", "dà bù fèn", "most of them", "kebanyakannya"],
    ["会", "huì", "will", "akan"],
    ["漂到", "piāo dào", "drift to", "hanyut ke"],
    ["新的", "xīn de", "new", "baharu"],
    ["障碍", "zhàng ài", "obstacles", "halangan"],
    ["那儿", "nà r", "there", "sana"],
    ["，", "", "", ""],
    ["挤成", "jǐ chéng", "squeeze into", "berkumpul menjadi"],
    ["白花花", "bái huā huā", "white and fluffy", "putih bersih"],
    ["的", "de", "", ""],
    ["一团", "yī tuán", "a cluster", "sekumpulan"],
    ["，", "", "", ""],
    ["老远", "lǎo yuǎn", "from afar", "dari jauh"],
    ["就可以", "jiù kě yǐ", "can", "boleh"],
    ["望见", "wàng jiàn", "see", "nampak"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第3段

    ["水", "shuǐ", "Water", "Air"],
    ["遇到", "yù dào", "encounters", "menemui"],
    ["一个又一个", "yī gè yòu yī gè", "one obstacle after another", "halangan demi halangan"],
    ["障碍", "zhàng ài", "obstacles", "halangan"],
    ["，", "", "", ""],
    ["却", "què", "yet", "tetapi"],
    ["毫不在乎", "háo bù zài hu", "doesn't care at all", "langsung tidak peduli"],
    ["，", "", "", ""],
    ["它", "tā", "it", "ia"],
    ["只是", "zhǐ shì", "just", "hanya"],
    ["聚集", "jù jí", "gather", "berkumpul"],
    ["为", "wéi", "into", "menjadi"],
    ["一股股", "yī gǔ gǔ", "streams of", "aliran-aliran"],
    ["水流", "shuǐ liú", "water flow", "aliran air"],
    ["，", "", "", ""],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["面临", "miàn lín", "facing", "menghadapi"],
    ["免不了", "miǎn bù liǎo", "inevitable", "tidak dapat dielakkan"],
    ["的", "de", "", ""],
    ["一场搏斗", "yī chǎng bó dòu", "a struggle", "pergelutan"],
    ["，", "", "", ""],
    ["收紧", "shōu jǐn", "tightening", "menegangkan"],
    ["肌肉", "jī ròu", "muscles", "otot"],
    ["一样", "yī yàng", "like", "seperti"],
    ["。", "", "", ""],
    ["水", "shuǐ", "The water", "Air"],
    ["颤动着", "chàn dòng zhe", "trembling", "bergetar"],
    ["，", "", "", ""],
    ["阳光", "yáng guāng", "sunlight", "cahaya matahari"],
    ["把", "bǎ", "", ""],
    ["颤动的", "chàn dòng de", "trembling", "bergetar"],
    ["水影", "shuǐ yǐng", "water shadows", "bayangan air"],
    ["投射到", "tóu shè dào", "cast onto", "memancar ke"],
    ["云杉树上", "yún shān shù shàng", "spruce trees", "pokok spruce"],
    ["和", "hé", "and", "dan"],
    ["青草上", "qīng cǎo shàng", "grass", "rumput"],
    ["，", "", "", ""],
    ["水影", "shuǐ yǐng", "water shadows", "bayangan air"],
    ["就在", "jiù zài", "just on", "terus di"],
    ["树干", "shù gàn", "trunks", "batang pokok"],
    ["和", "hé", "and", "dan"],
    ["青草上", "qīng cǎo shàng", "grass", "rumput"],
    ["忽闪", "hū shǎn", "flicker", "berkelip-kelip"],
    ["。", "", "", ""],
    ["水", "shuǐ", "Water", "Air"],
    ["在", "zài", "in", "dalam"],
    ["颤动中", "chàn dòng zhōng", "trembling", "getaran"],
    ["发出", "fā chū", "emits", "mengeluarkan"],
    ["淙淙声", "cóng cóng shēng", "gurgling sound", "bunyi gemericik"],
    ["，", "", "", ""],
    ["青草", "qīng cǎo", "grass", "rumput"],
    ["仿佛", "fǎng fú", "as if", "seolah-olah"],
    ["在", "zài", "in", "dalam"],
    ["这", "zhè", "this", "ini"],
    ["乐声中", "yuè shēng zhōng", "music", "bunyi muzik"],
    ["生长", "shēng zhǎng", "grow", "tumbuh"],
    ["，", "", "", ""],
    ["而", "ér", "and", "dan"],
    ["水影", "shuǐ yǐng", "water shadows", "bayangan air"],
    ["显得", "xiǎn de", "appear", "kelihatan"],
    ["是", "shì", "is", "ialah"],
    ["那么", "nà me", "so", "begitu"],
    ["调和", "tiáo hé", "harmonious", "harmoni"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第4段

    ["流过", "liú guò", "Flowing through", "Mengalir melalui"],
    ["一段", "yī duàn", "a stretch of", "sebahagian"],
    ["又浅又阔", "yòu qiǎn yòu kuò", "shallow and wide", "cetek dan lebar"],
    ["的", "de", "", ""],
    ["地方", "dì fang", "place", "tempat"],
    ["，", "", "", ""],
    ["水", "shuǐ", "water", "air"],
    ["急急注入", "jí jí zhù rù", "rushes into", "deras mengalir ke"],
    ["狭窄的", "xiá zhǎi de", "narrow", "sempit"],
    ["深水道", "shēn shuǐ dào", "deep channel", "saluran dalam"],
    ["，", "", "", ""],
    ["因为", "yīn wèi", "because", "kerana"],
    ["流得急", "liú de jí", "flows fast", "mengalir deras"],
    ["而", "ér", "and", "dan"],
    ["无声", "wú shēng", "silent", "senyap"],
    ["，", "", "", ""],
    ["就好像", "jiù hǎo xiàng", "as if", "seolah-olah"],
    ["在", "zài", "in", "dalam"],
    ["收紧", "shōu jǐn", "tightening", "menegangkan"],
    ["肌肉", "jī ròu", "muscles", "otot"],
    ["。", "", "", ""],
    ["太阳", "tài yáng", "The sun", "Matahari"],
    ["不甘寂寞", "bù gān jì mò", "not willing to be left out", "tidak mahu ketinggalan"],
    ["，", "", "", ""],
    ["让", "ràng", "lets", "membiarkan"],
    ["那", "nà", "those", "itu"],
    ["水流的", "shuǐ liú de", "water's", "aliran air punya"],
    ["紧张的", "jǐn zhāng de", "tense", "tegang"],
    ["影子", "yǐng zi", "shadows", "bayangan-bayangan"],
    ["在", "zài", "on", "di"],
    ["树干", "shù gàn", "trunks", "batang pokok"],
    ["和", "hé", "and", "dan"],
    ["青草上", "qīng cǎo shàng", "grass", "rumput"],
    ["不住地", "bù zhù de", "continuously", "tanpa henti"],
    ["忽闪", "hū shǎn", "flicker", "berkelip-kelip"],
    ["。", "", "", ""],
    ["太阳", "tài yáng", "The sun", "Matahari"],
    ["所", "suǒ", "", ""],
    ["反映的", "fǎn yìng de", "reflected", "yang dipantulkan"],
    ["水上", "shuǐ shàng", "on the water", "di atas air"],
    ["涟漪", "lián yī", "ripples", "riak-riak"],
    ["的影子", "de yǐng zi", "shadows", "bayangan"],
    ["，", "", "", ""],
    ["像", "xiàng", "like", "seperti"],
    ["轻烟", "qīng yān", "light smoke", "asap ringan"],
    ["似的", "shì de", "as if", "seolah-olah"],
    ["总在", "zǒng zài", "always", "sentiasa"],
    ["树上", "shù shàng", "trees", "pokok"],
    ["和", "hé", "and", "dan"],
    ["青草上", "qīng cǎo shàng", "grass", "rumput"],
    ["晃动着", "huàng dòng zhe", "swaying", "bergoyang"],
    ["。", "", "", ""],
    ["在", "zài", "In", "Dalam"],
    ["小溪", "xiǎo xī", "stream's", "sungai kecil punya"],
    ["的", "de", "", ""],
    ["淙淙声中", "cóng cóng shēng zhōng", "gurgling sound", "bunyi gemericik"],
    ["，", "", "", ""],
    ["饱含", "bǎo hán", "full of", "penuh dengan"],
    ["树脂", "shù zhī", "resin", "damar"],
    ["的", "de", "", ""],
    ["幼芽", "yòu yá", "buds", "tunas"],
    ["在", "zài", "are", "sedang"],
    ["开放", "kāi fàng", "opening", "mekar"],
    ["，", "", "", ""],
    ["水下的", "shuǐ xià de", "underwater", "di bawah air"],
    ["草", "cǎo", "grass", "rumput"],
    ["长出", "zhǎng chū", "grow out", "tumbuh keluar"],
    ["水面", "shuǐ miàn", "water surface", "permukaan air"],
    ["，", "", "", ""],
    ["岸上", "àn shàng", "on the bank", "di tebing"],
    ["青草", "qīng cǎo", "grass", "rumput"],
    ["越发", "yuè fā", "even more", "semakin"],
    ["繁茂", "fán mào", "luxuriant", "subur"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第5段

    ["这儿", "zhè r", "Here", "Di sini"],
    ["是", "shì", "is", "ialah"],
    ["一个", "yī gè", "a", "sebuah"],
    ["静静的", "jìng jìng de", "quiet", "tenang"],
    ["旋涡", "xuán wō", "eddy", "pusaran"],
    ["，", "", "", ""],
    ["旋涡中心", "xuán wō zhōng xīn", "eddy's center", "pusat pusaran"],
    ["是", "shì", "is", "ialah"],
    ["一棵", "yī kē", "a", "sebatang"],
    ["倒树", "dǎo shù", "fallen tree", "pokok tumbang"],
    ["，", "", "", ""],
    ["有几只", "yǒu jǐ zhī", "there are a few", "ada beberapa ekor"],
    ["亮闪闪的", "liàng shǎn shǎn de", "shiny", "berkilauan"],
    ["小甲虫", "xiǎo jiǎ chóng", "beetles", "kumbang kecil"],
    ["在", "zài", "on", "di"],
    ["平静的", "píng jìng de", "calm", "tenang"],
    ["水面上", "shuǐ miàn shàng", "water surface", "permukaan air"],
    ["打转", "dǎ zhuàn", "spinning", "berpusing-pusing"],
    ["，", "", "", ""],
    ["惹起了", "rě qǐ le", "causing", "menimbulkan"],
    ["粼粼涟漪", "lín lín lián yī", "ripples", "riak-riak"],
    ["。", "", "", ""],
    ["水流", "shuǐ liú", "The water flow", "Aliran air"],
    ["在", "zài", "in", "dalam"],
    ["克制的", "kè zhì de", "restrained", "terkawal"],
    ["嘟哝声中", "dū nong shēng zhōng", "murmur", "bunyi gumaman"],
    ["稳稳地", "wěn wěn de", "steadily", "dengan stabil"],
    ["流淌着", "liú tǎng zhe", "flows", "mengalir"],
    ["，", "", "", ""],
    ["它们", "tā men", "they", "mereka"],
    ["兴奋得", "xīng fèn de", "so excited", "begitu teruja"],
    ["不能不", "bù néng bù", "cannot help but", "tidak dapat tidak"],
    ["互相呼唤", "hù xiāng hū huàn", "call to each other", "saling memanggil"],
    ["：", "", "", ""],
    ["许多支", "xǔ duō zhī", "many streams of", "banyak aliran"],
    ["有力的水", "yǒu lì de shuǐ", "powerful water", "air yang kuat"],
    ["都", "dōu", "all", "semua"],
    ["流到了", "liú dào le", "flow to", "mengalir ke"],
    ["一起", "yī qǐ", "together", "bersama"],
    ["，", "", "", ""],
    ["汇合成", "huì hé chéng", "converge into", "bergabung menjadi"],
    ["了一股", "le yī gǔ", "a", "satu"],
    ["大的", "dà de", "big", "besar"],
    ["水流", "shuǐ liú", "flow", "aliran"],
    ["，", "", "", ""],
    ["彼此间", "bǐ cǐ jiān", "between each other", "antara satu sama lain"],
    ["又说话", "yòu shuō huà", "talk", "bercakap"],
    ["又呼唤", "yòu hū huàn", "call", "memanggil"],
    ["——", "", "", ""],
    ["这是", "zhè shì", "this is", "ini adalah"],
    ["所有", "suǒ yǒu", "all", "semua"],
    ["来到一起", "lái dào yī qǐ", "come together", "datang bersama"],
    ["又要分开的", "yòu yào fēn kāi de", "about to separate", "yang akan berpisah"],
    ["水流", "shuǐ liú", "water flows", "aliran-aliran air"],
    ["在", "zài", "in", "dalam"],
    ["打招呼呢", "dǎ zhāo hu ne", "greeting each other", "memberi salam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第6段

    ["水", "shuǐ", "Water", "Air"],
    ["惹动着", "rě dòng zhe", "stirs", "menggerakkan"],
    ["新结的", "xīn jié de", "newly formed", "yang baru terbentuk"],
    ["黄色花蕾", "huáng sè huā lěi", "yellow buds", "tunas bunga kuning"],
    ["，", "", "", ""],
    ["花蕾", "huā lěi", "buds", "tunas"],
    ["反又", "fǎn yòu", "in turn", "sebaliknya"],
    ["在水面", "zài shuǐ miàn", "on the water surface", "di permukaan air"],
    ["漾起", "yàng qǐ", "create", "menimbulkan"],
    ["波纹", "bō wén", "ripples", "riak-riak"],
    ["。", "", "", ""],
    ["小溪", "xiǎo xī", "The stream's", "Sungai kecil punya"],
    ["的", "de", "", ""],
    ["生活中", "shēng huó zhōng", "life", "kehidupan"],
    ["，", "", "", ""],
    ["就这样", "jiù zhè yàng", "just like this", "begitulah"],
    ["一会儿", "yī huì r", "sometimes", "kadang-kadang"],
    ["泡沫频起", "pào mò pín qǐ", "foam frequently rises", "buih sering timbul"],
    ["，", "", "", ""],
    ["一会儿", "yī huì r", "sometimes", "kadang-kadang"],
    ["在花", "zài huā", "among flowers", "di antara bunga"],
    ["和", "hé", "and", "dan"],
    ["晃动的影子间", "huàng dòng de yǐng zi jiān", "among flickering shadows", "di antara bayangan yang bergoyang"],
    ["发出", "fā chū", "emits", "mengeluarkan"],
    ["兴奋的", "xīng fèn de", "excited", "teruja"],
    ["招呼声", "zhāo hu shēng", "greetings", "salam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第7段

    ["有一棵树", "yǒu yī kē shù", "There is a tree", "Ada sebatang pokok"],
    ["早已", "zǎo yǐ", "already", "telah lama"],
    ["横堵在", "héng dǔ zài", "blocking", "menghalang di"],
    ["小溪上", "xiǎo xī shàng", "the stream", "sungai kecil"],
    ["，", "", "", ""],
    ["春天一到", "chūn tiān yī dào", "when spring comes", "apabila musim bunga tiba"],
    ["竟", "jìng", "actually", "rupanya"],
    ["还", "hái", "still", "masih"],
    ["长出了", "zhǎng chū le", "grew", "tumbuh"],
    ["新绿", "xīn lǜ", "new green", "hijau baru"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["小溪", "xiǎo xī", "the stream", "sungai kecil"],
    ["在树下", "zài shù xià", "under the tree", "di bawah pokok"],
    ["找到了", "zhǎo dào le", "found", "menemui"],
    ["出路", "chū lù", "way out", "jalan keluar"],
    ["，", "", "", ""],
    ["匆匆地", "cōng cōng de", "hurriedly", "dengan tergesa-gesa"],
    ["奔流着", "bēn liú zhe", "rushing", "mengalir deras"],
    ["，", "", "", ""],
    ["晃着", "huàng zhe", "swaying", "menggoyangkan"],
    ["颤动的", "chàn dòng de", "trembling", "bergetar"],
    ["水影", "shuǐ yǐng", "water shadows", "bayangan air"],
    ["，", "", "", ""],
    ["发出", "fā chū", "emitting", "mengeluarkan"],
    ["潺潺的声音", "chán chán de shēng yīn", "gurgling sound", "bunyi gemericik"],
    ["。", "", "", ""],
    ["有些草", "yǒu xiē cǎo", "Some grass", "Beberapa rumput"],
    ["早已", "zǎo yǐ", "already", "telah"],
    ["从水下", "cóng shuǐ xià", "from under the water", "dari bawah air"],
    ["钻出来了", "zuān chū lái le", "emerged", "telah keluar"],
    ["，", "", "", ""],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["立在", "lì zài", "standing in", "berdiri di"],
    ["溪流中", "xī liú zhōng", "the stream", "dalam aliran"],
    ["频频点头", "pín pín diǎn tóu", "nodding frequently", "sering mengangguk"],
    ["，", "", "", ""],
    ["算是", "suàn shì", "as", "sebagai"],
    ["既对", "jì duì", "both to", "kedua-duanya kepada"],
    ["影子的颤动", "yǐng zi de chàn dòng", "the trembling of shadows", "getaran bayangan"],
    ["又对", "yòu duì", "and to", "dan kepada"],
    ["小溪的奔流", "xiǎo xī de bēn liú", "the rushing stream", "aliran deras sungai kecil"],
    ["的", "de", "", ""],
    ["回答", "huí dá", "answer", "jawapan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第8段

    ["就让", "jiù ràng", "Let", "Biarkan"],
    ["路途当中", "lù tú dāng zhōng", "on the journey", "dalam perjalanan"],
    ["出现", "chū xiàn", "appear", "muncul"],
    ["阻塞", "zǔ sè", "obstructions", "sekatan"],
    ["吧", "ba", "", ""],
    ["，", "", "", ""],
    ["让它出现好了", "ràng tā chū xiàn hǎo le", "let them appear", "biarkan ia muncul"],
    ["！", "", "", ""],
    ["有障碍", "yǒu zhàng ài", "With obstacles", "Ada halangan"],
    ["，", "", "", ""],
    ["才有生活", "cái yǒu shēng huó", "there is life", "barulah ada kehidupan"],
    ["：", "", "", ""],
    ["要是没有的话", "yào shì méi yǒu de huà", "if not", "jika tiada"],
    ["，", "", "", ""],
    ["水", "shuǐ", "water", "air"],
    ["便会", "biàn huì", "would", "akan"],
    ["毫无生气地", "háo wú shēng qì de", "lifelessly", "tanpa semangat"],
    ["立刻", "lì kè", "immediately", "segera"],
    ["流入", "liú rù", "flow into", "mengalir ke"],
    ["大洋了", "dà yáng le", "the ocean", "lautan"],
    ["，", "", "", ""],
    ["就像", "jiù xiàng", "just like", "seperti"],
    ["不明不白的", "bù míng bù bái de", "meaningless", "tanpa erti"],
    ["生命", "shēng mìng", "life", "kehidupan"],
    ["离开", "lí kāi", "leaving", "meninggalkan"],
    ["毫无生气的", "háo wú shēng qì de", "lifeless", "tanpa semangat"],
    ["机体", "jī tǐ", "body", "jasad"],
    ["一样", "yī yàng", "like", "seperti"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第9段

    ["途中", "tú zhōng", "Along the way", "Di sepanjang jalan"],
    ["有", "yǒu", "there is", "ada"],
    ["一片", "yī piàn", "a stretch of", "sebidang"],
    ["宽阔的", "kuān kuò de", "wide", "luas"],
    ["洼地", "wā dì", "lowland", "tanah rendah"],
    ["。", "", "", ""],
    ["小溪", "xiǎo xī", "The stream", "Sungai kecil"],
    ["毫不吝啬地", "háo bù lìn sè de", "generously", "dengan murah hati"],
    ["将它", "jiāng tā", "it", "ia"],
    ["灌满", "guàn mǎn", "fills", "memenuhi"],
    ["水", "shuǐ", "with water", "air"],
    ["，", "", "", ""],
    ["并", "bìng", "and", "dan"],
    ["继续前行", "jì xù qián xíng", "continues forward", "terus ke hadapan"],
    ["，", "", "", ""],
    ["而", "ér", "while", "sementara"],
    ["留下", "liú xià", "leaving", "meninggalkan"],
    ["那水塘", "nà shuǐ táng", "that pond", "kolam itu"],
    ["过它", "guò tā", "live its", "menjalani"],
    ["自己的日子", "zì jǐ de rì zi", "own life", "kehidupannya sendiri"],
    ["。", "", "", ""],
    ["有一棵", "yǒu yī kē", "There is a", "Ada sebatang"],
    ["大灌木", "dà guàn mù", "big bush", "pokok renek besar"],
    ["被", "bèi", "was", "telah"],
    ["冬雪", "dōng xuě", "winter snow", "salji musim sejuk"],
    ["压弯了", "yā wān le", "bent", "dilenturkan"],
    ["，", "", "", ""],
    ["现在", "xiàn zài", "now", "sekarang"],
    ["有许多", "yǒu xǔ duō", "many", "banyak"],
    ["枝条", "zhī tiáo", "branches", "dahan-dahan"],
    ["垂挂到", "chuí guà dào", "hang down to", "tergantung ke"],
    ["小溪中", "xiǎo xī zhōng", "the stream", "sungai kecil"],
    ["，", "", "", ""],
    ["煞像", "shà xiàng", "just like", "sangat seperti"],
    ["一只", "yī zhī", "a", "seekor"],
    ["大蜘蛛", "dà zhī zhū", "big spider", "labah-labah besar"],
    ["，", "", "", ""],
    ["灰蒙蒙的", "huī méng méng de", "greyish", "kekelabuan"],
    ["，", "", "", ""],
    ["趴在水面上", "pā zài shuǐ miàn shàng", "lying on the water surface", "terbaring di permukaan air"],
    ["，", "", "", ""],
    ["轻轻摇晃着", "qīng qīng yáo huàng zhe", "gently shaking", "perlahan-lahan menggoncang"],
    ["所有", "suǒ yǒu", "all", "semua"],
    ["细长的腿", "xì cháng de tuǐ", "long thin legs", "kaki-kaki panjang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第10段

    ["云杉", "yún shān", "Spruce", "Spruce"],
    ["和", "hé", "and", "dan"],
    ["白杨", "bái yáng", "poplar", "poplar"],
    ["的", "de", "", ""],
    ["种子", "zhǒng zi", "seeds", "biji-bijian"],
    ["在", "zài", "are", "sedang"],
    ["漂浮着", "piāo fú zhe", "floating", "terapung"],
    ["。", "", "", ""],
    ["小溪", "xiǎo xī", "The stream", "Sungai kecil"],
    ["流经", "liú jīng", "flowing through", "mengalir melalui"],
    ["树林", "shù lín", "the forest", "hutan"],
    ["的", "de", "", ""],
    ["全程", "quán chéng", "entire journey", "keseluruhan perjalanan"],
    ["，", "", "", ""],
    ["是一条", "shì yī tiáo", "is a", "ialah sebatang"],
    ["充满", "chōng mǎn", "full of", "penuh dengan"],
    ["持续搏斗", "chí xù bó dòu", "continuous struggle", "pergelutan berterusan"],
    ["的", "de", "", ""],
    ["道路", "dào lù", "road", "jalan"],
    ["，", "", "", ""],
    ["时间", "shí jiān", "time", "masa"],
    ["就", "jiù", "then", "maka"],
    ["由此", "yóu cǐ", "from this", "daripada ini"],
    ["而被", "ér bèi", "is", "telah"],
    ["创造出来", "chuàng zào chū lái", "created", "diciptakan"],
    ["。", "", "", ""],
    ["搏斗", "bó dòu", "Struggle", "Pergelutan"],
    ["持续不断", "chí xù bù duàn", "continuous", "berterusan"],
    ["，", "", "", ""],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["和", "hé", "and", "dan"],
    ["我的", "wǒ de", "my", "saya punya"],
    ["意识", "yì shí", "consciousness", "kesedaran"],
    ["就", "jiù", "then", "maka"],
    ["在", "zài", "in", "dalam"],
    ["这", "zhè", "this", "ini"],
    ["持续不断中", "chí xù bù duàn zhōng", "continuity", "kesinambungan"],
    ["形成", "xíng chéng", "formed", "terbentuk"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第11段

    ["是的", "shì de", "Yes", "Ya"],
    ["，", "", "", ""],
    ["要是", "yào shì", "if", "jika"],
    ["每一步", "měi yī bù", "every step", "setiap langkah"],
    ["没有", "méi yǒu", "without", "tanpa"],
    ["这些", "zhè xiē", "these", "ini"],
    ["障碍", "zhàng ài", "obstacles", "halangan"],
    ["，", "", "", ""],
    ["水", "shuǐ", "water", "air"],
    ["就会", "jiù huì", "would", "akan"],
    ["立刻", "lì kè", "immediately", "segera"],
    ["流走了", "liú zǒu le", "flow away", "mengalir pergi"],
    ["，", "", "", ""],
    ["也就", "yě jiù", "then", "maka"],
    ["根本", "gēn běn", "completely", "langsung"],
    ["不会有", "bù huì yǒu", "there would be no", "tidak akan ada"],
    ["生活", "shēng huó", "life", "kehidupan"],
    ["和", "hé", "and", "dan"],
    ["时间了", "shí jiān le", "time", "masa"],
    ["……", "", "", ""],
    ["小溪", "xiǎo xī", "The stream", "Sungai kecil"],
    ["在", "zài", "in", "dalam"],
    ["搏斗中", "bó dòu zhōng", "struggle", "pergelutan"],
    ["竭尽", "jié jìn", "exerting", "menggunakan"],
    ["力量", "lì liàng", "strength", "kekuatan"],
    ["，", "", "", ""],
    ["溪中", "xī zhōng", "in the stream", "dalam sungai"],
    ["一股股水流", "yī gǔ gǔ shuǐ liú", "streams of water", "aliran-aliran air"],
    ["像", "xiàng", "like", "seperti"],
    ["肌肉似的", "jī ròu shì de", "like muscles", "seperti otot"],
    ["扭动着", "niǔ dòng zhe", "writhing", "bergeliat"],
    ["，", "", "", ""],
    ["但是", "dàn shì", "but", "tetapi"],
    ["毫无疑问的是", "háo wú yí wèn de shì", "without a doubt", "tidak dapat diragukan"],
    ["，", "", "", ""],
    ["小溪", "xiǎo xī", "the stream", "sungai kecil"],
    ["早晚会", "zǎo wǎn huì", "sooner or later will", "pasti akan"],
    ["流入", "liú rù", "flow into", "mengalir ke"],
    ["大洋的", "dà yáng de", "the ocean's", "lautan punya"],
    ["自由的", "zì yóu de", "free", "bebas"],
    ["水中", "shuǐ zhōng", "waters", "perairan"],
    ["，", "", "", ""],
    ["而这", "ér zhè", "and this", "dan ini"],
    ["“", "", "", ""],
    ["早晚", "zǎo wǎn", "sooner or later", "pasti"],
    ["”", "", "", ""],
    ["就", "jiù", "is", "ialah"],
    ["正是", "zhèng shì", "precisely", "itulah"],
    ["时间", "shí jiān", "time", "masa"],
    ["，", "", "", ""],
    ["正是生活", "zhèng shì shēng huó", "life", "kehidupan"],
    ["。", "", "", ""],
    ["一股股水流", "yī gǔ gǔ shuǐ liú", "Streams of water", "Aliran-aliran air"],
    ["在", "zài", "in", "dalam"],
    ["两岸紧夹中", "liǎng àn jǐn jiā zhōng", "between tight banks", "di antara tebing yang rapat"],
    ["奋力前进", "fèn lì qián jìn", "advance with effort", "maju dengan usaha"],
    ["，", "", "", ""],
    ["彼此呼唤", "bǐ cǐ hū huàn", "calling to each other", "saling memanggil"],
    ["，", "", "", ""],
    ["说着", "shuō zhe", "saying", "berkata"],
    ["“", "", "", ""],
    ["早晚", "zǎo wǎn", "sooner or later", "pasti"],
    ["”", "", "", ""],
    ["二字", "èr zì", "these two words", "dua perkataan ini"],
    ["。", "", "", ""],
    ["这", "zhè", "This", "Ini"],
    ["“", "", "", ""],
    ["早晚", "zǎo wǎn", "sooner or later", "pasti"],
    ["”", "", "", ""],
    ["之声", "zhī shēng", "sound", "bunyi"],
    ["整天整夜地", "zhěng tiān zhěng yè de", "day and night", "siang dan malam"],
    ["响个不断", "xiǎng ge bù duàn", "sounds without end", "berbunyi tanpa henti"],
    ["。", "", "", ""],
    ["当", "dāng", "When", "Apabila"],
    ["最后一滴水", "zuì hòu yī dī shuǐ", "the last drop of water", "titisan air terakhir"],
    ["还没有流完", "hái méi yǒu liú wán", "has not finished flowing", "belum selesai mengalir"],
    ["，", "", "", ""],
    ["当", "dāng", "when", "apabila"],
    ["春天的小溪", "chūn tiān de xiǎo xī", "the spring stream", "sungai kecil musim bunga"],
    ["还没有干涸", "hái méi yǒu gān hé", "has not dried up", "belum kering"],
    ["的时候", "de shí hou", "", ""],
    ["，", "", "", ""],
    ["水", "shuǐ", "water", "air"],
    ["总是不倦地", "zǒng shì bù juàn de", "always tirelessly", "sentiasa tanpa lelah"],
    ["反复说着", "fǎn fù shuō zhe", "repeats", "berulang kali berkata"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["我们", "wǒ men", "We", "Kita"],
    ["早晚会", "zǎo wǎn huì", "sooner or later will", "pasti akan"],
    ["流入", "liú rù", "flow into", "mengalir ke"],
    ["大洋", "dà yáng", "the ocean", "lautan"],
    ["。”", "", "", ""],

    ["\n", "", "", ""], // 👈 第12段

    ["流净了", "liú jìng le", "Flowed clean", "Air mengalir bersih"],
    ["冰的", "bīng de", "ice", "ais"],
    ["岸边", "àn biān", "bank", "tebing"],
    ["，", "", "", ""],
    ["有一个", "yǒu yī gè", "there is a", "ada sebuah"],
    ["圆形的", "yuán xíng de", "round", "bulat"],
    ["水湾", "shuǐ wān", "bay", "teluk kecil"],
    ["。", "", "", ""],
    ["一条", "yī tiáo", "A", "Seekor"],
    ["在", "zài", "during", "semasa"],
    ["发大水时", "fā dà shuǐ shí", "flood", "air bah"],
    ["留下的", "liú xià de", "left behind", "yang ditinggalkan"],
    ["小狗鱼", "xiǎo gǒu yú", "small pike", "ikan pike kecil"],
    ["，", "", "", ""],
    ["被困在", "bèi kùn zài", "trapped in", "terperangkap dalam"],
    ["这水湾的", "zhè shuǐ wān de", "this bay's", "teluk kecil ini punya"],
    ["春水中", "chūn shuǐ zhōng", "spring waters", "air musim bunga"],
    ["。", "", "", ""],
    ["你", "nǐ", "You", "Awak"],
    ["顺着", "shùn zhe", "along", "menyusuri"],
    ["小溪", "xiǎo xī", "the stream", "sungai kecil"],
    ["会", "huì", "will", "akan"],
    ["突然", "tū rán", "suddenly", "tiba-tiba"],
    ["来到", "lái dào", "come to", "sampai ke"],
    ["一个", "yī gè", "a", "sebuah"],
    ["宁静的地方", "níng jìng de dì fang", "peaceful place", "tempat yang tenang"],
    ["，", "", "", ""],
    ["你会听见", "nǐ huì tīng jiàn", "you will hear", "awak akan mendengar"],
    ["，", "", "", ""],
    ["一只灰雀", "yī zhī huī què", "a bullfinch's", "seekor burung pipit"],
    ["的低鸣", "de dī míng", "low call", "bunyi rendah"],
    ["和", "hé", "and", "dan"],
    ["一只苍头燕雀", "yī zhī cāng tóu yàn què", "a chaffinch's", "seekor burung pipit"],
    ["惹动", "rě dòng", "stirring", "menggerakkan"],
    ["枯叶", "kū yè", "dead leaves", "daun kering"],
    ["的簌簌声", "de sù sù shēng", "rustling sound", "bunyi desiran"],
    ["竟会", "jìng huì", "actually would", "rupanya akan"],
    ["响遍", "xiǎng biàn", "resound through", "bergema di"],
    ["整个树林", "zhěng gè shù lín", "the whole forest", "seluruh hutan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第13段

    ["有时", "yǒu shí", "Sometimes", "Kadang-kadang"],
    ["一些", "yī xiē", "some", "beberapa"],
    ["强大的", "qiáng dà de", "powerful", "kuat"],
    ["水流", "shuǐ liú", "water flows", "aliran air"],
    ["，", "", "", ""],
    ["或者", "huò zhě", "or", "atau"],
    ["有两股水", "yǒu liǎng gǔ shuǐ", "two streams", "dua aliran"],
    ["的", "de", "", ""],
    ["小溪", "xiǎo xī", "streams", "sungai kecil"],
    ["，", "", "", ""],
    ["呈斜角形", "chéng xié jiǎo xíng", "at an angle", "berbentuk sudut"],
    ["汇合起来", "huì hé qǐ lái", "converge", "bergabung"],
    ["，", "", "", ""],
    ["全力冲击着", "quán lì chōng jī zhe", "forcefully impact", "dengan kuat menghentam"],
    ["被", "bèi", "by", "oleh"],
    ["百年云杉", "bǎi nián yún shān", "century-old spruce", "spruce berusia seratus tahun"],
    ["的", "de", "", ""],
    ["许多", "xǔ duō", "many", "banyak"],
    ["粗壮树根", "cū zhuàng shù gēn", "thick roots", "akar tebal"],
    ["所加固的", "suǒ jiā gù de", "reinforced", "yang diperkukuh"],
    ["陡岸", "dǒu àn", "steep bank", "tebing curam"],
    ["。", "", "", ""],
    ["真惬意啊", "zhēn qiè yì a", "How delightful", "Sungguh menyenangkan"],
    ["：", "", "", ""],
    ["我", "wǒ", "I", "saya"],
    ["坐在", "zuò zài", "sit on", "duduk di"],
    ["树根上", "shù gēn shàng", "the roots", "akar"],
    ["，", "", "", ""],
    ["一边休息", "yī biān xiū xī", "resting", "berehat"],
    ["，", "", "", ""],
    ["一边听", "yī biān tīng", "listening", "sambil mendengar"],
    ["陡岸下面", "dǒu àn xià miàn", "below the steep bank", "di bawah tebing curam"],
    ["强大的", "qiáng dà de", "powerful", "kuat"],
    ["水流", "shuǐ liú", "water flow", "aliran air"],
    ["不急不忙地", "bù jí bù máng de", "leisurely", "dengan tenang"],
    ["彼此呼唤", "bǐ cǐ hū huàn", "calling to each other", "saling memanggil"],
    ["，", "", "", ""],
    ["听它们", "tīng tā men", "listening to them", "mendengar mereka"],
    ["满怀", "mǎn huái", "full of", "penuh dengan"],
    ["“", "", "", ""],
    ["早晚", "zǎo wǎn", "sooner or later", "pasti"],
    ["”", "", "", ""],
    ["必到", "bì dào", "will surely reach", "pasti akan sampai"],
    ["大洋的", "dà yáng de", "the ocean", "lautan punya"],
    ["信心", "xìn xīn", "confidence", "keyakinan"],
    ["互打招呼", "hù dǎ zhāo hu", "greeting each other", "saling memberi salam"],
    ["……", "", "", ""]
];
